# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# openness_modelbuilder.py
# Created on: 2018-08-15 13:45:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")
arcpy.ImportToolbox("C:/saga-6.4.0_x64/ArcSAGA Toolboxes/Terrain Analysis - Lighting, Visibility.pyt")


# Local variables:
GeoTiffDEM_32 = "I:\\GeoTiffDEM_32"
Name = "MN_000_077_dem"
Input = "I:\GeoTiffDEM_32"
MN_000_077_dem_tif = "I:\\GeoTiffDEM_32\\MN_000_077_dem.tif"
v_NAME__POS_tif = "I:\\Openness\\Temp\\%NAME%_POS.tif"
v_NAME__NEG_tif = "I:\\Openness\\Temp\\%NAME%_NEG.tif"
v_NAME__PminusN_tif = "I:\\Openness\\Temp\\%NAME%_PminusN.tif"
Input_raster_or_constant_value_2 = "2"
v_NAME__Open_tif = "I:\\Openness\\Final_output\\%NAME%_Open.tif"

# Process: Iterate Rasters
arcpy.IterateRasters_mb(GeoTiffDEM_32, "", "TIF", "NOT_RECURSIVE")

# Process: Topographic Openness
arcpy.gp.toolbox = "C:/saga-6.4.0_x64/ArcSAGA Toolboxes/Terrain Analysis - Lighting, Visibility.pyt";
# Warning: the toolbox C:/saga-6.4.0_x64/ArcSAGA Toolboxes/Terrain Analysis - Lighting, Visibility.pyt DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.tool_5(...) with arcpy.tool_5_ALIAS(...)
arcpy.gp.tool_5(MN_000_077_dem_tif, v_NAME__POS_tif, v_NAME__NEG_tif, "50", "sectors", "3", "8")

# Process: Minus
arcpy.Minus_3d(v_NAME__POS_tif, v_NAME__NEG_tif, v_NAME__PminusN_tif)

# Process: Divide
arcpy.Divide_3d(v_NAME__PminusN_tif, Input_raster_or_constant_value_2, v_NAME__Open_tif)
#
